### ISSUE TITLE
subsites are not created

### ISSUE THREAD

**Issue by pieterverbrugge** [VeeamHub/vbo365-rest-self-service#1]
Hi 

maybe i'm doing something wrong but the subsites Exchange, Onedrive and Sharepoint are not created. Also it is not counting the licenses correctly.

the VBO365 version i'm using is the latest one from the veeam website.

contact me if needed.

Greetings

**Comment by nielsengelen** [comment]
Hi Pieter,

Could you give some more information on the server you are trying to run the webportal on? Is this a Linux or Windows server and which webservice is running on top of it?

**Comment by pieterverbrugge** [comment]
Hi niels

The server is running win2016 standard with iis. Fully up to date. With latest php x64. Changed the php.ini with the cache extension. Php is running fine cause phpinfo returns the correct info

Greetings
________________________________

**Comment by RichardSwart** [comment]
Have the same issue. I can see the jobs, repositories etc. But when I click on the Exchange, SharePoint or Onedrive pages. I get a 404 not found. Also running Server Std 2016, IIS and PHP 7.2.

**Comment by nielsengelen** [comment]
This is related due to IIS not supporting the .htaccess file which needs to be rewritten. I will update the readme with the correct steps to perform this. Normally the guide explained on https://blogs.msdn.microsoft.com/azureossds/2015/04/23/converting-apache-htaccess-rules-to-iis-web-config-using-iis-manager-for-azure-websites/ should be sufficient.

**Comment by RichardSwart** [comment]
Thanks for the prompt response, all working now :)

**Comment by nielsengelen** [comment]
Closing the issue as the solution is to rewrite the htaccess to a web config xml file.
