### ISSUE TITLE
export to pst

### ISSUE THREAD

**Issue by gingerr6** [VeeamHub/vbo365-rest-self-service#25]
2 problems,

when exporting to PST from a remote connection e.g outside the veeam server the export does nothing.
when doing it from a local web browser in the veeam server it fails.
![image](https://user-images.githubusercontent.com/74706187/99701979-2554c580-2a8d-11eb-875c-2aa9802e42e8.png)

**Comment by nielsengelen** [comment]
Do you have Outlook installed on the server running VBO?

**Comment by gingerr6** [comment]
not on the VBO, i do on my laptop (external of the VBO) and the export to PST doesn't work, there is no error.
export to MSG works.

**Comment by nielsengelen** [comment]
In order to export to a PST file, it is required to install Outlook on the VBO server as stated in the [Veeam Backup for Microsoft Office 365 user guide](https://helpcenter.veeam.com/docs/vbo365/rest/post_restore_sessions_id_organization_action.html?ver=40). I'll look into adjusting the error message to state this. It looks like this error got broken in a recent build and I've labeled it as a bug.

**Comment by gingerr6** [comment]
OK, the restore still isn't working windows 10 with outlook installed.

**Comment by nielsengelen** [comment]
It looks like you have multiple issues in either the VBO installation or within the API service. For the export to PST, there should also be information in the logs that may clarify some things.

**Comment by nielsengelen** [comment]
Empty error message will be resolved in the next version of the portal.
