### ISSUE TITLE
Load more button - sorting

### ISSUE THREAD

**Issue by adentimg** [VeeamHub/vbo365-rest-self-service#41]
**Describe the bug**
When loading more mailboxes, it only loads then for viewing on the left side panel and it adds the additional mailboxes at the bottom of the list NOT in alphabetical order.

**To Reproduce**

Go to self service Portal and login to the page
Click on Select a Date and click Start Restore
Scroll down to bottom of mailbox list
click on load more mailboxes
![image](https://user-images.githubusercontent.com/90589205/133019259-51652b1b-7270-4c1b-b57b-9580f527a5fc.png)
![image](https://user-images.githubusercontent.com/90589205/133019268-52ed63f1-6c07-493b-84e0-386869c2439a.png)

**Expected behavior**
Should load the list in both the left panel and main list in alphabetical order. There is also no in built way to search for a mailbox within the portal other than ctrl-f through the web browser.

Thanks!

**Comment by nielsengelen** [comment]
Hi, this is currently by design. Sorting is not directly available via the API which means loading is random and it would require a serious alternation in the current portal. 

Regarding a search (or better said a filter), this may be something I add in the future as an enhancement. Thanks for the idea.

**Comment by adentimg** [comment]
Hi Niels,

Thanks for the response! Looking forward to having a filter added in the future.
